[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sohamk4", email = "soham56kadam@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "langchain-core>=1.6.3",
    "langgraph>=1.2.11",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
code = "code:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
